<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Imp_model extends CI_Model
{

	public function get_tahun()
	{
		$this->db->distinct();
		$this->db->select('YEAR(TANGGAL) AS TAHUN');
		$this->db->from('TR_INDIKATOR');
		$this->db->order_by("YEAR(TANGGAL)", "desc");

		return $this->db->get();
	}

	public function get_det_ruang($id_ruang_sub)
	{
		$this->db->select('*');
		$this->db->from('TREF_RUANG_SUB');
		$this->db->where('ID', $id_ruang_sub);
		$query = $this->db->get();
		if ($query->num_rows() == 0) {
			return $data = 0;
		} else {
			return $query->row();
		}
	}

	public function get_capaian_imp_rs($tahun)
	{
		$query = $this->db->query("SELECT DISTINCT  DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_SEP,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS NUM_OKT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,
		
		((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
	AS TOTAL_NUM,
	
		((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
	AS TOTAL_DEN				
	FROM TR_INDIKATOR
	INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
	--WHERE TM_INDIKATOR.ID_RUANG = '3'
	where TM_INDIKATOR.F_IMP_RS = '1'
	and TM_INDIKATOR.F_STATUS = '1'
	AND YEAR(TANGGAL) = '$tahun'
	GROUP BY  DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR

							ORDER BY TM_INDIKATOR.DETAIL_INDIKATOR ASC");

		return $query;
	}
	// 
	// End Rekap IMP-RS
	//	

	public function get_capaian_imp_unit($tahun)
	{
		$query = $this->db->query("select * from (SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_SEP,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS NUM_OKT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,
		
		((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
	AS TOTAL_NUM,
	
		((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
	AS TOTAL_DEN				
	FROM TR_INDIKATOR
	INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
	--WHERE TM_INDIKATOR.ID_RUANG = '3'
	where TM_INDIKATOR.F_IMP_UNIT = '1'
	--and TM_INDIKATOR.F_STATUS = '1'
	AND YEAR(TANGGAL) = '$tahun'
	GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR

	) as A union (
	
	SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_SEP,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS NUM_OKT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
		SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,
		
		((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
	AS TOTAL_NUM,
	
		((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
		(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
	AS TOTAL_DEN				
	FROM TR_INDIKATOR
	INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
	--WHERE TM_INDIKATOR.ID_RUANG = '3'
	where 
				--IMP UNIT PERINA
	TM_INDIKATOR.ID = '23'
	and TR_INDIKATOR.ID_RUANG_SUB = '10002'
	--and TM_INDIKATOR.F_STATUS = '1'
	AND YEAR(TANGGAL) = '$tahun'
	GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR
	) 

				ORDER BY A.DETAIL_INDIKATOR ASC");

		return $query;
	}
	// 
	// End Rekap IMP-UNIT
	//	
}
