<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Rekap_model extends CI_Model
{

	public function get_total_perbulan($bulan)
	{
		$this->db->distinct();
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', $bulan);
		return $this->db->get()->num_rows();
	}

	public function get_data_bulanan($id_indikator, $id_ruang_sub, $bulan, $tahun)
	{
		$this->db->select('TR_INDIKATOR.ID, TR_INDIKATOR.TANGGAL, YEAR(TANGGAL) AS TAHUN, MONTH(TANGGAL) AS BULAN, DAY(TANGGAL) AS DATE, TR_INDIKATOR.NUM, TR_INDIKATOR.DEN, TREF_RUANG.NAMA_RUANG, TM_INDIKATOR.DETAIL_INDIKATOR, TM_INDIKATOR.DETAIL_NUM, TM_INDIKATOR.DETAIL_DEN');
		$this->db->from('TR_INDIKATOR');
		$this->db->join('TREF_RUANG_SUB', 'TR_INDIKATOR.ID_RUANG_SUB = TREF_RUANG_SUB.ID');
		$this->db->join('TREF_RUANG', 'TREF_RUANG_SUB.ID_RUANG = TREF_RUANG.ID');
		$this->db->join('TM_INDIKATOR', 'TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID');
		$this->db->where('TR_INDIKATOR.ID_INDIKATOR', $id_indikator);
		$this->db->where('TR_INDIKATOR.ID_RUANG_SUB', $id_ruang_sub);
		$this->db->where('YEAR(TR_INDIKATOR.TANGGAL)', $tahun);
		$this->db->where('MONTH(TR_INDIKATOR.TANGGAL)', $bulan);
		$this->db->where('TM_INDIKATOR.F_STATUS', 1);
		$this->db->order_by('TR_INDIKATOR.TANGGAL', 'ASC');
		return $this->db->get();
	}

	public function get_ruang()
	{
		return $this->db->get('TREF_RUANG_SUB');
	}

	public function get_det_ruang($id_ruang_sub)
	{
		$this->db->select('*');
		$this->db->from('TREF_RUANG_SUB');
		$this->db->where('ID', $id_ruang_sub);
		$query = $this->db->get();
		if ($query->num_rows() == 0) {
			return $data = 0;
		} else {
			return $query->row();
		}
	}

	public function get_tahun()
	{
		$this->db->distinct();
		$this->db->select('YEAR(TANGGAL) AS TAHUN');
		$this->db->from('TR_INDIKATOR');
		$this->db->order_by('YEAR(TANGGAL)', 'DESC');

		return $this->db->get();
	}

	public function get_indikator_ruang($id_ruang)
	{
		$this->db->select('*');
		$this->db->from('TM_INDIKATOR');
		$this->db->where('TM_INDIKATOR.ID_RUANG', $id_ruang);
		$this->db->where('F_STATUS', 1);
		return $this->db->get();
	}

	public function get_hari_hari($id_ruang_sub, $bulan, $tahun)
	{
		$this->db->distinct();
		$this->db->select('TANGGAL, DAY(TANGGAL) AS DATE');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('ID_RUANG_SUB', $id_ruang_sub);
		$this->db->where('MONTH(TANGGAL)', $bulan);
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->order_by('TANGGAL', 'ASC');
		$this->db->group_by('TANGGAL');
		return $this->db->get();
	}

	// 
	// Start Rekap triwulan
	//
	public function get_triwulan_i($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS AVG_NUM_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS AVG_NUM_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS AVG_NUM_MAR,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS AVG_DEN_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS AVG_DEN_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS AVG_DEN_MAR,

					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN,

					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}

	public function get_triwulan_ii($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,


					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS AVG_NUM_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS AVG_NUM_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS AVG_NUM_JUN,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS AVG_DEN_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS AVG_DEN_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS AVG_DEN_JUN,

					((SUM(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN,

					((AVG(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR 
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}

	public function get_triwulan_iii($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_SEP,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS AVG_NUM_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_SEP,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS AVG_DEN_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS AVG_DEN_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS AVG_DEN_SEP,

					((SUM(CASE WHEN DATEPART(m,TANGGAL)= '07' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN,

					((AVG(CASE WHEN DATEPART(m,TANGGAL)= '07' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR 
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}

	public function get_triwulan_iv($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS AVG_NUM_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS AVG_NUM_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS AVG_NUM_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS AVG_DEN_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS AVG_DEN_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS AVG_DEN_DES,

					((SUM(CASE WHEN DATEPART(m,TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN,

				((AVG(CASE WHEN DATEPART(m,TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR 
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}

	public function get_triwulan_dewas($tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS AVG_NUM_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS AVG_NUM_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS AVG_NUM_MAR,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS AVG_DEN_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS AVG_DEN_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS AVG_DEN_MAR,

					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM_TW_I,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN_TW_I,

					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM_TW_I,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN_TW_I,

				SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,


					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS AVG_NUM_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS AVG_NUM_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS AVG_NUM_JUN,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS AVG_DEN_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS AVG_DEN_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS AVG_DEN_JUN,

					((SUM(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM_TW_II,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN_TW_II,

					((AVG(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM_TW_II,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN_TW_II,

				SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_SEP,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS AVG_NUM_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_SEP,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS AVG_DEN_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS AVG_DEN_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS AVG_DEN_SEP,

					((SUM(CASE WHEN DATEPART(m,TANGGAL)= '07' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM_TW_III,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN_TW_III,

					((AVG(CASE WHEN DATEPART(m,TANGGAL)= '07' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM_TW_III,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN_TW_III

			FROM TR_INDIKATOR 
			INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
			WHERE TM_INDIKATOR.ID_RUANG = '3'
			AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
			GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
			ORDER BY TM_INDIKATOR.ID ASC
			");
		return $query;
	}

	public function get_triwulan_dewas_one_room($id_ruang, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS AVG_NUM_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS AVG_NUM_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS AVG_NUM_MAR,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS AVG_DEN_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS AVG_DEN_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS AVG_DEN_MAR,

					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM_TW_I,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN_TW_I,

					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM_TW_I,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN_TW_I,

				SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,


					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS AVG_NUM_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS AVG_NUM_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS AVG_NUM_JUN,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS AVG_DEN_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS AVG_DEN_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS AVG_DEN_JUN,

					((SUM(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM_TW_II,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN_TW_II,

					((AVG(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM_TW_II,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN_TW_II,

				SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_SEP,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS AVG_NUM_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_SEP,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS AVG_DEN_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS AVG_DEN_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS AVG_DEN_SEP,

					((SUM(CASE WHEN DATEPART(m,TANGGAL)= '07' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM_TW_III,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)))
				AS TOTAL_DEN_TW_III,

					((AVG(CASE WHEN DATEPART(m,TANGGAL)= '07' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM_TW_III,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)))
				AS AVG_TOTAL_DEN_TW_III

			FROM TR_INDIKATOR 
			INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
			WHERE TM_INDIKATOR.ID_RUANG = '$id_ruang'
			AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
			GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
			ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}
	// 
	// End Rekap triwulan
	//

	//
	// Start Rekap Semester
	//
	public function get_semester_i($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS AVG_NUM_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS AVG_NUM_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS AVG_NUM_MAR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS AVG_NUM_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS AVG_NUM_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS AVG_NUM_JUN,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS AVG_DEN_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS AVG_DEN_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS AVG_DEN_MAR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS AVG_DEN_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS AVG_DEN_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS AVG_DEN_JUN,

					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
						AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
						AS TOTAL_DEN,

					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '03' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
						AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '06' THEN NUM ELSE 0 END)))
						AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}

	public function get_semester_ii($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_SEP,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS NUM_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS AVG_NUM_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS AVG_NUM_SEP,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS AVG_NUM_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS AVG_NUM_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS AVG_NUM_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS AVG_DEN_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS AVG_DEN_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS AVG_DEN_SEP,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS AVG_DEN_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS AVG_DEN_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS AVG_DEN_DES,

					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m,TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS TOTAL_DEN,

					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '09' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m,TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}
	//
	// End Rekap Semester
	//




	// 
	// Start Rekap Tahunan
	//
	public function get_tahunan($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_SEP,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS NUM_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS AVG_NUM_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS AVG_NUM_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS AVG_NUM_MAR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS AVG_NUM_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS AVG_NUM_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS AVG_NUM_JUN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS AVG_NUM_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS AVG_NUM_SEP,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS AVG_NUM_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS AVG_NUM_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS AVG_NUM_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS AVG_DEN_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS AVG_DEN_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS AVG_DEN_MAR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS AVG_DEN_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS AVG_DEN_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS AVG_DEN_JUN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS AVG_DEN_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS AVG_DEN_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS AVG_DEN_SEP,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS AVG_DEN_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS AVG_DEN_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS AVG_DEN_DES,

					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS TOTAL_DEN,

					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}
	// 
	// End Rekap Tahunan
	//

	// 
	// Start Rekap Capaian
	//
	public function get_capaian($id_ruang_sub, $tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_SEP,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS NUM_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,

					SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
					SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS AVG_NUM_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS AVG_NUM_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS AVG_NUM_MAR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS AVG_NUM_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS AVG_NUM_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS AVG_NUM_JUN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS AVG_NUM_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS AVG_NUM_SEP,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS AVG_NUM_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS AVG_NUM_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS AVG_NUM_DES,

					AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS AVG_DEN_JAN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS AVG_DEN_FEB,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS AVG_DEN_MAR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS AVG_DEN_APR,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS AVG_DEN_MEI,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS AVG_DEN_JUN,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS AVG_DEN_JUL,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS AVG_DEN_AGT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS AVG_DEN_SEP,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS AVG_DEN_OKT,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS AVG_DEN_NOV,
					AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS AVG_DEN_DES,

					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS TOTAL_NUM,
					((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS TOTAL_DEN,

					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_NUM,
					((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
					(AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
				AS AVG_TOTAL_DEN

				FROM TR_INDIKATOR
				INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
				WHERE TR_INDIKATOR.ID_RUANG_SUB = '$id_ruang_sub'
				AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
				GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR
				ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}

	public function get_capaian_ranap($tahun)
	{
		$query = $this->db->query("SELECT DISTINCT TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS NUM_JAN,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS NUM_FEB,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS NUM_MAR,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS NUM_APR,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS NUM_MEI,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS NUM_JUN,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS NUM_JUL,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS NUM_AGT,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS NUM_SEP,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS NUM_OKT,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS NUM_NOV,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS NUM_DES,

				SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS DEN_JAN,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS DEN_FEB,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS DEN_MAR,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS DEN_APR,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS DEN_MEI,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS DEN_JUN,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS DEN_JUL,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS DEN_AGT,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS DEN_SEP,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS DEN_OKT,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS DEN_NOV,
				SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS DEN_DES,

				AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END) AS AVG_NUM_JAN,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END) AS AVG_NUM_FEB,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END) AS AVG_NUM_MAR,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END) AS AVG_NUM_APR,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END) AS AVG_NUM_MEI,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END) AS AVG_NUM_JUN,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END) AS AVG_NUM_JUL,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END) AS AVG_NUM_AGT,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END) AS AVG_NUM_SEP,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END) AS AVG_NUM_OKT,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END) AS AVG_NUM_NOV,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END) AS AVG_NUM_DES,

				AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END) AS AVG_DEN_JAN,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END) AS AVG_DEN_FEB,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END) AS AVG_DEN_MAR,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN DEN ELSE 0 END) AS AVG_DEN_APR,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN DEN ELSE 0 END) AS AVG_DEN_MEI,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN DEN ELSE 0 END) AS AVG_DEN_JUN,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END) AS AVG_DEN_JUL,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END) AS AVG_DEN_AGT,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END) AS AVG_DEN_SEP,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN DEN ELSE 0 END) AS AVG_DEN_OKT,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN DEN ELSE 0 END) AS AVG_DEN_NOV,
				AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN DEN ELSE 0 END) AS AVG_DEN_DES,

				((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
			AS TOTAL_NUM,
			
				((SUM(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
				(SUM(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
			AS TOTAL_DEN,

				((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN NUM ELSE 0 END)) + 
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN NUM ELSE 0 END)) + 
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
			AS AVG_TOTAL_NUM,
				((AVG(CASE WHEN DATEPART(m, TANGGAL)= '01' THEN DEN ELSE 0 END)) + 
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '02' THEN DEN ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '03' THEN DEN ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '04' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '05' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '06' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '07' THEN DEN ELSE 0 END)) + 
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '08' THEN DEN ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '09' THEN DEN ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '10' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '11' THEN NUM ELSE 0 END)) +
				(AVG(CASE WHEN DATEPART(m, TANGGAL)= '12' THEN NUM ELSE 0 END)))
			AS AVG_TOTAL_DEN

			FROM TR_INDIKATOR
			INNER JOIN TM_INDIKATOR ON TR_INDIKATOR.ID_INDIKATOR = TM_INDIKATOR.ID
			WHERE TM_INDIKATOR.ID_RUANG = '3'
			AND FORMAT (TANGGAL, 'yyyy') = '$tahun'
			GROUP BY TM_INDIKATOR.ID, DETAIL_INDIKATOR, DETAIL_NUM, DETAIL_DEN, NILAI_STANDAR
			ORDER BY TM_INDIKATOR.ID ASC");
		return $query;
	}
	// 
	// End Rekap Capaian
	//	


	public function get_det_indikator($id_ruang)
	{
		$this->db->select('ID, DETAIL_INDIKATOR');
		$this->db->from('TM_INDIKATOR');
		$this->db->where('ID_RUANG', $id_ruang);
		$this->db->limit(1);
		return $this->db->get()->row();
	}


	// Start Get Total Input Bulanan Per Tahun
	public function get_tt_hari_jan($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '1');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_feb($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '2');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_mar($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '3');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_apr($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '4');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_mei($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '5');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_jun($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '6');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_jul($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '7');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_agt($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '8');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_sep($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '9');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_okt($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '10');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_nov($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '11');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}

	public function get_tt_hari_des($tahun, $id_indikator)
	{
		$this->db->select('TANGGAL');
		$this->db->from('TR_INDIKATOR');
		$this->db->where('MONTH(TANGGAL)', '12');
		$this->db->where('YEAR(TANGGAL)', $tahun);
		$this->db->where('ID_INDIKATOR', $id_indikator);
		$query = $this->db->get()->num_rows();
		if ($query == 0) {
			$val = 1;
			return $val;
		} else {
			return $query;
		}
	}
	// End Get Total Input Bulanan Per Tahun
}
